// Shared constants for rarity system + game economy
// Used by convex/users.ts, convex/rng.ts, convex/shop.ts

// --- Rarity roster (hardcoded): 50 base + 450 rebirth rarities = 500 total ---
export const RARITIES = [
  "Common",
  "Uncommon",
  "Rare",
  "Epic",
  "Legendary",
  "Mythical",
  "Divine",
  "Prismatic",
  "Transcendent",
  "Unique",
  "Star",
  "Nova",
  "Comet",
  "Meteor",
  "Asteroid",
  "Nebula",
  "Galaxy",
  "Quasar",
  "Pulsar",
  "Supernova",
  "Hypernova",
  "Eclipse",
  "Aurora",
  "Zenith",
  "Vertex",
  "Apex",
  "Radiant",
  "Obsidian",
  "Crimson",
  "Azure",
  "Violet",
  "Golden",
  "Silver",
  "Cosmic",
  "Lunar",
  "Solar",
  "Stellar",
  "Inferno",
  "Glacier",
  "Tempest",
  "Mirage",
  "Phantom",
  "Specter",
  "Wraith",
  "Halo",
  "Onyx",
  "Titan",
  "Hydra",
  "Phoenix",
  "Griffin",
  "Basilisk",
  "Leviathan",
  "Wyvern",
  "Seraph",
  "Chimera",
  "Valkyrie",
  "Ragnarok",
  "Odyssey",
  "Paragon",
  "Velarion",
  "Veleth",
  "Velindra",
  "Veloros",
  "Velune",
  "Velexia",
  "Velosir",
  "Velumbra",
  "Velyrris",
  "Velaelis",
  "Velion",
  "Velara",
  "Veleska",
  "Veloltis",
  "Velynth",
  "Velaxis",
  "Velimel",
  "Velorrak",
  "Velustis",
  "Velavore",
  "Velenix",
  "Veloria",
  "Velulith",
  "Velarnex",
  "Velessia",
  "Velolym",
  "Velireth",
  "Velunox",
  "Velaleth",
  "Velirion",
  "Velovex",
  "Velysara",
  "Velandor",
  "Velelior",
  "Veluxis",
  "Velornia",
  "Velathis",
  "Velelyx",
  "Velurion",
  "Velaxia",
  "Korarion",
  "Koreth",
  "Korindra",
  "Kororos",
  "Korune",
  "Korexia",
  "Korosir",
  "Korumbra",
  "Koryrris",
  "Koraelis",
  "Korion",
  "Korara",
  "Koreska",
  "Koroltis",
  "Korynth",
  "Koraxis",
  "Korimel",
  "Kororrak",
  "Korustis",
  "Koravore",
  "Korenix",
  "Kororia",
  "Korulith",
  "Korarnex",
  "Koressia",
  "Korolym",
  "Korireth",
  "Korunox",
  "Koraleth",
  "Koririon",
  "Korovex",
  "Korysara",
  "Korandor",
  "Korelior",
  "Koruxis",
  "Korornia",
  "Korathis",
  "Korelyx",
  "Korurion",
  "Koraxia",
  "Zanarion",
  "Zaneth",
  "Zanindra",
  "Zanoros",
  "Zanune",
  "Zanexia",
  "Zanosir",
  "Zanumbra",
  "Zanyrris",
  "Zanaelis",
  "Zanion",
  "Zanara",
  "Zaneska",
  "Zanoltis",
  "Zanynth",
  "Zanaxis",
  "Zanimel",
  "Zanorrak",
  "Zanustis",
  "Zanavore",
  "Zanenix",
  "Zanoria",
  "Zanulith",
  "Zanarnex",
  "Zanessia",
  "Zanolym",
  "Zanireth",
  "Zanunox",
  "Zanaleth",
  "Zanirion",
  "Zanovex",
  "Zanysara",
  "Zanandor",
  "Zanelior",
  "Zanuxis",
  "Zanornia",
  "Zanathis",
  "Zanelyx",
  "Zanurion",
  "Zanaxia",
  "Thalarion",
  "Thaleth",
  "Thalindra",
  "Thaloros",
  "Thalune",
  "Thalexia",
  "Thalosir",
  "Thalumbra",
  "Thalyrris",
  "Thalaelis",
  "Thalion",
  "Thalara",
  "Thaleska",
  "Thaloltis",
  "Thalynth",
  "Thalaxis",
  "Thalimel",
  "Thalorrak",
  "Thalustis",
  "Thalavore",
  "Thalenix",
  "Thaloria",
  "Thalulith",
  "Thalarnex",
  "Thalessia",
  "Thalolym",
  "Thalireth",
  "Thalunox",
  "Thalaleth",
  "Thalirion",
  "Thalovex",
  "Thalysara",
  "Thalandor",
  "Thalelior",
  "Thaluxis",
  "Thalornia",
  "Thalathis",
  "Thalelyx",
  "Thalurion",
  "Thalaxia",
  "Oriarion",
  "Orieth",
  "Oriindra",
  "Orioros",
  "Oriune",
  "Oriexia",
  "Oriosir",
  "Oriumbra",
  "Oriyrris",
  "Oriaelis",
  "Oriion",
  "Oriara",
  "Orieska",
  "Orioltis",
  "Oriynth",
  "Oriaxis",
  "Oriimel",
  "Oriorrak",
  "Oriustis",
  "Oriavore",
  "Orienix",
  "Orioria",
  "Oriulith",
  "Oriarnex",
  "Oriessia",
  "Oriolym",
  "Oriireth",
  "Oriunox",
  "Orialeth",
  "Oriirion",
  "Oriovex",
  "Oriysara",
  "Oriandor",
  "Orielior",
  "Oriuxis",
  "Oriornia",
  "Oriathis",
  "Orielyx",
  "Oriurion",
  "Oriaxia",
  "Nyxarion",
  "Nyxeth",
  "Nyxindra",
  "Nyxoros",
  "Nyxune",
  "Nyxexia",
  "Nyxosir",
  "Nyxumbra",
  "Nyxyrris",
  "Nyxaelis",
  "Nyxion",
  "Nyxara",
  "Nyxeska",
  "Nyxoltis",
  "Nyxynth",
  "Nyxaxis",
  "Nyximel",
  "Nyxorrak",
  "Nyxustis",
  "Nyxavore",
  "Nyxenix",
  "Nyxoria",
  "Nyxulith",
  "Nyxarnex",
  "Nyxessia",
  "Nyxolym",
  "Nyxireth",
  "Nyxunox",
  "Nyxaleth",
  "Nyxirion",
  "Nyxovex",
  "Nyxysara",
  "Nyxandor",
  "Nyxelior",
  "Nyxuxis",
  "Nyxornia",
  "Nyxathis",
  "Nyxelyx",
  "Nyxurion",
  "Nyxaxia",
  "Caelarion",
  "Caeleth",
  "Caelindra",
  "Caeloros",
  "Caelune",
  "Caelexia",
  "Caelosir",
  "Caelumbra",
  "Caelyrris",
  "Caelaelis",
  "Caelion",
  "Caelara",
  "Caeleska",
  "Caeloltis",
  "Caelynth",
  "Caelaxis",
  "Caelimel",
  "Caelorrak",
  "Caelustis",
  "Caelavore",
  "Caelenix",
  "Caeloria",
  "Caelulith",
  "Caelarnex",
  "Caelessia",
  "Caelolym",
  "Caelireth",
  "Caelunox",
  "Caelaleth",
  "Caelirion",
  "Caelovex",
  "Caelysara",
  "Caelandor",
  "Caelelior",
  "Caeluxis",
  "Caelornia",
  "Caelathis",
  "Caelelyx",
  "Caelurion",
  "Caelaxia",
  "Draarion",
  "Draeth",
  "Draindra",
  "Draoros",
  "Draune",
  "Draexia",
  "Draosir",
  "Draumbra",
  "Drayrris",
  "Draaelis",
  "Draion",
  "Draara",
  "Draeska",
  "Draoltis",
  "Draynth",
  "Draaxis",
  "Draimel",
  "Draorrak",
  "Draustis",
  "Draavore",
  "Draenix",
  "Draoria",
  "Draulith",
  "Draarnex",
  "Draessia",
  "Draolym",
  "Draireth",
  "Draunox",
  "Draaleth",
  "Drairion",
  "Draovex",
  "Draysara",
  "Draandor",
  "Draelior",
  "Drauxis",
  "Draornia",
  "Draathis",
  "Draelyx",
  "Draurion",
  "Draaxia",
  "Morarion",
  "Moreth",
  "Morindra",
  "Mororos",
  "Morune",
  "Morexia",
  "Morosir",
  "Morumbra",
  "Moryrris",
  "Moraelis",
  "Morion",
  "Morara",
  "Moreska",
  "Moroltis",
  "Morynth",
  "Moraxis",
  "Morimel",
  "Mororrak",
  "Morustis",
  "Moravore",
  "Morenix",
  "Mororia",
  "Morulith",
  "Morarnex",
  "Moressia",
  "Morolym",
  "Morireth",
  "Morunox",
  "Moraleth",
  "Moririon",
  "Morovex",
  "Morysara",
  "Morandor",
  "Morelior",
  "Moruxis",
  "Morornia",
  "Morathis",
  "Morelyx",
  "Morurion",
  "Moraxia",
  "Solarion",
  "Soleth",
  "Solindra",
  "Soloros",
  "Solune",
  "Solexia",
  "Solosir",
  "Solumbra",
  "Solyrris",
  "Solaelis",
  "Solion",
  "Solara",
  "Soleska",
  "Sololtis",
  "Solynth",
  "Solaxis",
  "Solimel",
  "Solorrak",
  "Solustis",
  "Solavore",
  "Solenix",
  "Soloria",
  "Solulith",
  "Solarnex",
  "Solessia",
  "Sololym",
  "Solireth",
  "Solunox",
  "Solaleth",
  "Solirion",
  "Solovex",
  "Solysara",
  "Solandor",
  "Solelior",
  "Soluxis",
  "Solornia",
  "Solathis",
  "Solelyx",
  "Solurion",
  "Solaxia",
  "Umbraarion",
  "Umbraeth",
  "Umbraindra",
  "Umbraoros",
  "Umbraune",
  "Umbraexia",
  "Umbraosir",
  "Umbraumbra",
  "Umbrayrris",
  "Umbraaelis",
  "Umbraion",
  "Umbraara",
  "Umbraeska",
  "Umbraoltis",
  "Umbraynth",
  "Umbraaxis",
  "Umbraimel",
  "Umbraorrak",
  "Umbraustis",
  "Umbraavore",
  "Umbraenix",
  "Umbraoria",
  "Umbraulith",
  "Umbraarnex",
  "Umbraessia",
  "Umbraolym",
  "Umbraireth",
  "Umbraunox",
  "Umbraaleth",
  "Umbrairion",
  "Umbraovex",
  "Umbraysara",
  "Umbraandor",
  "Umbraelior",
  "Umbrauxis",
  "Umbraornia",
  "Umbraathis",
  "Umbraelyx",
  "Umbraurion",
  "Umbraaxia",
  "Fenarion",
];

export const TOTAL_RARITY_COUNT = RARITIES.length;

export const WEIGHTS = [
  500000, 250000, 125000, 62500, 31250, 15625, 7812, 3906, 1953, 976, 488, 244, 122, 61, 30,
  15, 7, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
  44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 43, 43, 43, 43, 43,
  43, 43, 43, 43, 43, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 40, 40, 40, 40, 40,
  40, 40, 40, 40, 40, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
  38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37, 37, 37, 37, 37,
  37, 37, 37, 37, 37, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
  35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 34, 34, 34, 34, 34,
  34, 34, 34, 34, 34, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
  32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 31, 31, 31, 31, 31,
  31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
  29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 28, 28, 28, 28, 28,
  28, 28, 28, 28, 28, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
  26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 25, 25, 25, 25, 25,
  25, 25, 25, 25, 25, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
  23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 22, 22, 22, 22, 22,
  22, 22, 22, 22, 22, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
  20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 19, 19, 19, 19, 19,
  19, 19, 19, 19, 19, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
  17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 16, 16, 16, 16, 16,
  16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
  14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13,
  13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
  11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10,
  10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
  8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7,
  7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
  5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1
];

export const RARITY_VALUES = Array.from({ length: TOTAL_RARITY_COUNT }, (_, i) =>
  Math.min(2500, Math.round(Math.pow(i + 1, 1.25)))
);

// --- Game economy ---
export const BASE_RARITY_COUNT = 50;
export const RARITIES_PER_REBIRTH = 10;
export const MAX_REBIRTHS = 45; // 50 + 45 * 10 = 500 total rarities
export const TOTAL_RARITIES = 500;

// Roll cost ladder. The first roll is free; then the ladder cycles forever:
// 1 (x10), 2 (x5), 4 (x3), 8 (x1), then back to 1...
export const ROLL_COST_LADDER = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 4, 4, 4, 8];
export const ROLL_COST_LADDER_LEN = ROLL_COST_LADDER.length;

/** Cost of the next roll, based on how many rolls the user has done (0 = first roll, free). */
export function rollCostFor(rollCount: number): number {
  if (rollCount <= 0) return 0;
  return ROLL_COST_LADDER[(rollCount - 1) % ROLL_COST_LADDER_LEN];
}

/** Total rarities available after N rebirths. */
export function totalRaritiesFor(rebirthCount: number): number {
  return Math.min(BASE_RARITY_COUNT + rebirthCount * RARITIES_PER_REBIRTH, TOTAL_RARITIES);
}

export const TOP_TIER_SIZE = 10;

export interface AchievementStats {
  rollCount: number;
  rebirthCount: number;
  distinctCaught: number;
  completedGame: boolean;
  luckbucks: number;
  ownsTopTierPull: boolean;
}

export const ACHIEVEMENTS: ReadonlyArray<{
  id: string;
  name: string;
  description: string;
  check: (s: AchievementStats) => boolean;
}> = [
  { id: 'first-roll', name: 'First Roll', description: 'Roll the reel once', check: (s) => s.rollCount >= 1 },
  { id: 'century', name: 'Century Club', description: 'Roll 100 times', check: (s) => s.rollCount >= 100 },
  { id: 'roll-machine', name: 'Roll Machine', description: 'Roll 1,000 times', check: (s) => s.rollCount >= 1000 },
  { id: 'reborn', name: 'Reborn', description: 'Rebirth for the first time', check: (s) => s.rebirthCount >= 1 },
  { id: 'phoenix', name: 'Phoenix', description: 'Rebirth 5 times', check: (s) => s.rebirthCount >= 5 },
  { id: 'collector', name: 'Collector', description: 'Own 25 distinct rarities', check: (s) => s.distinctCaught >= 25 },
  { id: 'curator', name: 'Curator', description: 'Own 100 distinct rarities', check: (s) => s.distinctCaught >= 100 },
  { id: 'halfway', name: 'Halfway There', description: 'Own 250 distinct rarities', check: (s) => s.distinctCaught >= 250 },
  { id: 'completionist', name: 'Completionist', description: 'Catch every rarity', check: (s) => s.completedGame },
  { id: 'high-roller', name: 'High Roller', description: 'Hold 1,000 LuckBucks at once', check: (s) => s.luckbucks >= 1000 },
  { id: 'elite-pull', name: 'Elite Pull', description: 'Currently own a top-tier rarity', check: (s) => s.ownsTopTierPull },
];

export function evaluateAchievements(stats: AchievementStats): Array<{ id: string; unlocked: boolean }> {
  return ACHIEVEMENTS.map(({ id, check }) => ({ id, unlocked: check(stats) }));
}

export function computeBulkSale(
  counts: Record<string, number>,
  maxSellValue: number
): { earned: number; itemsSold: number; remainingCounts: Record<string, number> } {
  const remainingCounts = { ...counts };
  let earned = 0;
  let itemsSold = 0;

  for (const [rarity, count] of Object.entries(counts)) {
    const idx = RARITIES.indexOf(rarity);
    if (idx < 0) continue;
    const valuePerItem = RARITY_VALUES[idx];
    if (valuePerItem > maxSellValue || count <= 0) continue;
    earned += valuePerItem * count;
    itemsSold += count;
    delete remainingCounts[rarity];
  }

  return { earned, itemsSold, remainingCounts };
}

export const LEADERBOARD_MIN_VALUE = 20;


export const PRESTIGE_SELL_BONUS = 0.25;

export function prestigeMultiplier(prestigeCount: number): number {
  return Math.min(4, 1 + PRESTIGE_SELL_BONUS * Math.max(0, prestigeCount));
}

// ── Mini arcade economy ──────────────────────────────────────────────
// Server-authoritative side bets. Every payout is computed from these
// constants on the server; the client only animates the result.
// Every game is negative-EV by construction (~4% house edge): grinding
// cannot print LuckBucks, so no play limits are needed.

export const ARCADE = {
  coin: { cost: 5, win: 9 },
  plinko: { cost: 10 },
  hilo: { cost: 10, payoutPct: 0.96 },
  wheel: { cost: 25 },
  dice: { cost: 10, payoutPct: 0.96 },
  mines: { cost: 10, payoutPct: 0.96, tiles: 9, mines: 3, maxPicks: 4 },
  slots: { cost: 5 },
  limbo: { cost: 10, payoutPct: 0.96, minTarget: 1.1, maxTarget: 50 },
  cups: { cost: 5, cups: 3, payoutMult: 2.88 },
} as const;

// Binomial 8-row walk. Edge-weighted so EV = 249.2/256 ≈ 0.97 against the stake.
export const PLINKO_MULTS = [6, 1, 0.5, 1.6, 0.2, 1.6, 0.5, 1, 6];
// Uniform 8 segments, sum 7.5 → EV = 7.5/8 = 0.9375.
export const WHEEL_MULTS = [0, 1, 0, 1.5, 0, 1, 0, 5];
export const WHEEL_LABELS = WHEEL_MULTS.map((m) => (m === 5 ? 'JACKPOT' : `x${m}`));

export function arcadePayout(cost: number, mult: number): number {
  return Math.floor(cost * mult);
}

// Slots: weighted reels. EV ≈ 0.964 (triples + any-pair paytable).
export const SLOTS_SYMBOLS = ['SEVEN', 'GEM', 'BOLT', 'MOON', 'BELL', 'STAR'] as const;
export type SlotsSymbol = (typeof SLOTS_SYMBOLS)[number];
export const SLOTS_WEIGHTS: Record<SlotsSymbol, number> = {
  SEVEN: 1,
  GEM: 2,
  BOLT: 3,
  MOON: 4,
  BELL: 6,
  STAR: 8,
};
export const SLOTS_TRIPLE_PAY: Record<SlotsSymbol, number> = {
  SEVEN: 50,
  GEM: 20,
  BOLT: 10,
  MOON: 6,
  BELL: 4,
  STAR: 2.5,
};
export const SLOTS_PAIR_PAY = 1.5;
